# Generated by Django 3.2.9 on 2021-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cempresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_consumidor',
            field=models.BooleanField(default=False),
        ),
    ]
